#!/usr/bin/env python3
"""Test correct model propagation through recursion levels."""

print("=" * 80)
print("Correct Model Propagation Test")
print("=" * 80)
print()

print("Key Insight:")
print("- recursive_models[0] = model for level 0's recursive calls")
print("- When creating RLM_REPL at level 1, its root model should be recursive_models[1]")
print("- When creating RLM_REPL at level 2, its root model should be recursive_models[2]")
print()
print("=" * 80)
print()

recursive_models = ["gpt-5-mini", "llama-3.1-70b", "llama-3.1-8b"]
max_depth = 3

print(f"Model List: {recursive_models}")
print(f"max_depth = {max_depth}")
print()
print("=" * 80)
print("Call Chain with Correct Model Propagation:")
print("=" * 80)
print()

print("Level 0 (Root):")
print("  RLM_REPL(model='gpt-5', current_depth=0, max_depth=3)")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv checks if should_recurse")
print("      should_recurse = (0 + 1) < 3 = True")
print("      └─> Creates RLM_REPL for level 1")
print(f"          model = recursive_models[1] = '{recursive_models[1]}'")
print()

print("Level 1:")
print(f"  RLM_REPL(model='{recursive_models[1]}', current_depth=1, max_depth=3)")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv checks if should_recurse")
print("      should_recurse = (1 + 1) < 3 = True")
print("      └─> Creates RLM_REPL for level 2")
print(f"          model = recursive_models[2] = '{recursive_models[2]}'")
print()

print("Level 2:")
print(f"  RLM_REPL(model='{recursive_models[2]}', current_depth=2, max_depth=3)")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv checks if should_recurse")
print("      should_recurse = (2 + 1) < 3 = False")
print("      └─> Creates Sub_RLM (BASE CASE)")
print(f"          model = recursive_models[2] = '{recursive_models[2]}'")
print()

print("=" * 80)
print("Summary of Root Models at Each Level:")
print("=" * 80)
print()
print(f"Level 0 (Root):    'gpt-5' (from RLM_REPL's model parameter)")
print(f"Level 1:           '{recursive_models[1]}' (from recursive_models[1])")
print(f"Level 2:           '{recursive_models[2]}' (from recursive_models[2])")
print(f"Base Case:         '{recursive_models[2]}' (from recursive_models[2])")
print()
print("=" * 80)
print("Key Points:")
print("=" * 80)
print()
print("1. Root RLM_REPL uses its own 'model' parameter (default: 'gpt-5')")
print("2. recursive_models[0] is used for root's recursive calls (level 0 → level 1)")
print("3. When creating RLM_REPL at level N, its root model = recursive_models[N]")
print("4. This creates a cascade where each level uses the next model in the list")
print("5. Base case (Sub_RLM) uses recursive_models[current_depth]")
print()
print("✓ Logic is now correct!")
