#!/usr/bin/env python3
"""Test user's specific example."""

print("=" * 80)
print("User Example: model='gpt-5', recursive_models=['1', '2', '3'], max_depth=3")
print("=" * 80)
print()

model = 'gpt-5'
recursive_models = ['1', '2', '3']
max_depth = 3

print(f"Initialization:")
print(f"  RLM_REPL(model='{model}', recursive_models={recursive_models}, max_depth={max_depth})")
print()
print("=" * 80)
print("Call Chain:")
print("=" * 80)
print()

print("Level 0 (Root):")
print(f"  RLM_REPL(model='{model}', current_depth=0, max_depth={max_depth})")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv creates sub_rlm")
print("      current_depth = 0, so current_model = recursive_models[0] = '1'")
print("      should_recurse = (0 + 1) < 3 = True")
print("      next_model = current_model = '1' (use current depth's model for next level)")
print("      └─> Creates RLM_REPL for level 1")
print()

print("Level 1:")
print(f"  RLM_REPL(model='{recursive_models[0]}', current_depth=1, max_depth={max_depth})")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv creates sub_rlm")
print("      current_depth = 1, so current_model = recursive_models[1] = '2'")
print("      should_recurse = (1 + 1) < 3 = True")
print("      next_model = current_model = '2' (use current depth's model for next level)")
print("      └─> Creates RLM_REPL for level 2")
print()

print("Level 2:")
print(f"  RLM_REPL(model='{recursive_models[1]}', current_depth=2, max_depth={max_depth})")
print(f"  recursive_models = {recursive_models}")
print("  └─> REPLEnv creates sub_rlm")
print("      current_depth = 2, so current_model = recursive_models[2] = '3'")
print("      should_recurse = (2 + 1) < 3 = False")
print("      └─> Creates Sub_RLM (BASE CASE)")
print()

print("=" * 80)
print("Summary:")
print("=" * 80)
print()
print(f"Root model: '{model}'")
print(f"recursive_models: {recursive_models}")
print(f"max_depth: {max_depth}")
print()
print("Created Structure:")
print(f"  Root RLM_REPL(model='{model}')")
print(f"    └─> RLM_REPL(model='{recursive_models[0]}')")
print(f"         └─> RLM_REPL(model='{recursive_models[1]}')")
print(f"              └─> Sub_RLM(model='{recursive_models[2]}')")
print()
print("Key Points:")
print("- Root uses 'model' parameter: 'gpt-5'")
print("- Level 1 uses recursive_models[0]: '1'")
print("- Level 2 uses recursive_models[1]: '2'")
print("- Base case uses recursive_models[2]: '3'")
print("- All models in recursive_models are used!")
print()
