#!/usr/bin/env python3
"""Test to verify root model vs recursive models don't interfere."""

print("=" * 80)
print("Root Model vs Recursive Models")
print("=" * 80)
print()

print("Two Separate Model Parameters:")
print("-" * 80)
print()
print("1. 'model' parameter:")
print("   - Used by the RLM_REPL itself (the root LLM)")
print("   - Default: 'gpt-5'")
print("   - Environment variable: LLM_MODEL")
print("   - Used for the main completion loop")
print()
print("2. 'recursive_models' parameter:")
print("   - Used for recursive calls (sub-RLMs)")
print("   - Default: ['gpt-5-mini']")
print("   - Environment variable: LLM_RECURSIVE_MODEL")
print("   - Used when creating Sub_RLM or nested RLM_REPL instances")
print()
print("=" * 80)
print()

print("Example 1: Default behavior")
print("-" * 80)
print()
print("rlm = RLM_REPL()")
print("  → root model: 'gpt-5'")
print("  → recursive_models: ['gpt-5-mini']")
print("  → root uses 'gpt-5', recursive calls use 'gpt-5-mini'")
print()

print("Example 2: Custom root model, default recursive models")
print("-" * 80)
print()
print("rlm = RLM_REPL(model='gpt-4o')")
print("  → root model: 'gpt-4o'")
print("  → recursive_models: ['gpt-5-mini']")
print("  → root uses 'gpt-4o', recursive calls use 'gpt-5-mini'")
print()

print("Example 3: Default root model, custom recursive models")
print("-" * 80)
print()
print("rlm = RLM_REPL(recursive_models=['llama-3.1-70b', 'llama-3.1-8b'])")
print("  → root model: 'gpt-5'")
print("  → recursive_models: ['llama-3.1-70b', 'llama-3.1-8b']")
print("  → root uses 'gpt-5', recursive calls use 'llama-3.1-70b' then 'llama-3.1-8b'")
print()

print("Example 4: Custom both root and recursive models")
print("-" * 80)
print()
print("rlm = RLM_REPL(")
print("    model='gpt-4o',")
print("    recursive_models=['llama-3.1-70b', 'llama-3.1-8b'],")
print("    max_depth=3")
print(")")
print()
print("Call Chain:")
print("  Root RLM_REPL(model='gpt-4o', current_depth=0)")
print("    └─> Creates RLM_REPL(current_depth=1, uses 'llama-3.1-70b')")
print("         └─> Creates RLM_REPL(current_depth=2, uses 'llama-3.1-8b')")
print("              └─> Creates Sub_RLM(model='llama-3.1-8b') ← BASE CASE")
print()

print("=" * 80)
print("Conclusion: No Interference!")
print("=" * 80)
print()
print("✓ 'model' and 'recursive_models' are completely separate")
print("✓ Root uses 'model' for its own LLM calls")
print("✓ Recursive calls use 'recursive_models' list")
print("✓ They can be different models without any conflict")
print("✓ This is the intended design")
